### ISSUE TITLE
Integration tests fail due to SSLHandshakeException

### ISSUE THREAD

**Issue by rhoegg** [avioconsulting/mule-azure-key-vault-connector#23]
Here's output from maven. I suspect an expired certificate in the keystore.  I will work up a PR.

**Comment by rhoegg** [comment]
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   AkvIntegrationTestCase.invalidTlsTest:224 
Expected: a string containing "Error retrieving secret"
     but: was "javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target."
[ERROR] Errors: 
[ERROR]   AkvIntegrationTestCase.decryptKeyTest » Messaging The user, group or applicati...
[ERROR]   AkvIntegrationTestCase.encryptKeyTest » Messaging The user, group or applicati...
[ERROR]   AkvIntegrationTestCase.validTlsTest » Messaging javax.net.ssl.SSLHandshakeExce...
[INFO] 
[ERROR] Tests run: 18, Failures: 1, Errors: 3, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

**Comment by rhoegg** [comment]
This turned out to be a masked error, in fact. The access policy for my key vault did not grant Encrypt or Decrypt permission to my service principal, and the integration tests reported an SSL handshake error instead of the real problem.

![Screen Shot 2021-07-07 at 5 57 45 PM](https://user-images.githubusercontent.com/44559/124838684-f7a18b80-df4c-11eb-9794-57a0d5bee467.png)

Once I corrected the permissions, all the integration tests save one passed. There is still a problem with the invalidTlsTest. It seems to expect a proper mule error, but instead gets a low level SSL handshake exception.

![Screen Shot 2021-07-07 at 5 56 07 PM](https://user-images.githubusercontent.com/44559/124838770-2455a300-df4d-11eb-9fcc-9ede89eca115.png)

I believe the issue is that login.microsoftonline.com and vault.azure.com do not currently use the same root CA for their certificates.

**Comment by kkingavio** [comment]
Re-created truststore in demo project.  Fixed in 1.2.1 Release
