### ISSUE TITLE
Connector returns [TokenExpired] Error validating token: 'S2S12086'. after some time.

### ISSUE THREAD

**Issue by chawlaharpreet89** [avioconsulting/mule-azure-key-vault-connector#27]
The access token is not refreshed and the APIs using the connector components return "**[TokenExpired] Error validating token: 'S2S12086'.**" error.
Can you suggest if I am missing something in the config or it is an issue with the connector?

@kkingavio

**Comment by jyoung** [comment]
I've run into the same issue. 
You may try using the [Azure Key Vault REST API](https://docs.microsoft.com/en-us/rest/api/keyvault/). 
This [article](https://technicalblogs.sentientmindz.com/2021/12/31/accessing-secrets-from-azure-key-vault-in-a-mulesoft-application/) helped quite a lot.

**Comment by kkingavio** [comment]
Fixed in the latest 1.2.1 Release.  Thanks for your help!
